package br.com.wiskyacademy.hotel.templates;

public enum FixtureCoreTemplates {
  VALIDO,
  VALIDO_SEM_ID,
  VALIDO_OUTRO_NOME_E_DESCRICAO,
  VALIDO_OUTRO_NOME_E_DOCUMENTO,
  VALIDO_CAPACIDADE_BAIXA,
  VALIDO_CAPACIDADE_ALTA,
  VALIDO_PRECO_BAIXO,
  VALIDO_PRECO_ALTO
}