server:
  port: 8080

spring:
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379
  datasource:
    url: jdbc:mysql://localhost:3306/hotel
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        order_inserts: true
    hibernate.ddl-auto: validate
    generate-ddl: false
    show-sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false