server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hotel
    username: root
    password: root
  jpa:
    hibernate.ddl-auto: validate
    generate-ddl: false
    show-sql: true