name: Coverage
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
permissions: read-all
jobs:
  coverage:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0
      - uses: actions/setup-go@v3
        with:
          go-version: 1.17
      - name: coverage
        run: make coverage
