name: Lint
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
permissions: read-all
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.17
      - name: lint
        run: make lint
